version: '3'
services:
  ray_serve_tutorial:
    build: .
    user: root
    container_name: ray_serve_tutorial
    ports:
      - "8888:8888"
      - "9000:9000"
      - "8000:8000"
      - "8265:8265"
      - "9090:9090"
      - "5001:5001"
      - "6379:6379"
      - "9001:9001"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8089:8089"

    volumes:
      - ./workspace:/ray_serve_tutorial/workspace
    restart: "no"